# ╔══════════════════════════════════════╗
# ║         Gruvbox Dark                ║
# ║  source this in hyprlock.conf       ║
# ╚══════════════════════════════════════╝

$foreground  = rgb(ebdbb2)
$backgroundCol = rgb(282828)

$color0  = rgb(282828)   # bg
$color1  = rgb(cc241d)   # red
$color2  = rgb(98971a)   # green
$color3  = rgb(d79921)   # yellow
$color4  = rgb(458588)   # blue
$color5  = rgb(b16286)   # purple
$color6  = rgb(689d6a)   # aqua
$color7  = rgb(a89984)   # fg4
$color8  = rgb(928374)   # gray
$color9  = rgb(fb4934)   # bright red
$color10 = rgb(b8bb26)   # bright green
$color11 = rgb(fabd2f)   # bright yellow
$color12 = rgb(83a598)   # bright blue
$color13 = rgb(d3869b)   # bright purple
$color14 = rgb(8ec07c)   # bright aqua
$color15 = rgb(ebdbb2)   # fg
