wallpaper {
    monitor = eDP-1
    path = ~/.config/walls/wallpaper7.png
    fit_mode = cover
}

wallpaper {
    monitor = HDMI-A-1
    path = ~/.config/walls/wallpaper7.png
    fit_mode = cover
}
splash = off
